Fixes an exception when not declared var is used.
To reproduce the bug:

    echo 'begin formula $a and $b end formula' | ./external/touistc -sat /dev/stdin -o /dev/stdout -table /dev/stdout
Result:

    Fatal error: exception File "src/eval.ml", line 379, characters 16-21: Pattern matching failed

@olzd lines 350 to 390 are quite lousely writen for now (weird failwith messages for example)