chore(opam): fix error "<package>.install missing"
The error was:

    % opam exec -- dune uninstall
    Error: The following <package>.install are missing:
    - _build/default/touist.install
    Hint: try running: dune build @install